version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: daily
    open-pull-requests-limit: 1

  - package-ecosystem: rust-toolchain
    directory: /src-tauri
    schedule:
      interval: daily
    open-pull-requests-limit: 1

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
