[env]
BINDGEN_EXTRA_CLANG_ARGS = "-I/opt/homebrew/include -I/usr/local/include"
SYSTEM_DEPS_LIBCDIO_LINK = "static"
SYSTEM_DEPS_LIBCDIO_CDDA_LINK = "static"
SYSTEM_DEPS_LIBCDIO_PARANOIA_LINK = "static"
